---
title: "Lab 02 - Global plastic waste"
author: "Team Name: Cameron"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message = FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
```


## Load & join data sets

```{r load-data, message = FALSE}
# Member 2 (pair 1) write code to load File 1 data here:
data1 <- read_csv("data/mismanaged-plastic-waste-per-capita.csv")

# Member 4 (pair 2) write code to load File 2 data here:
data2 <- read_csv2("data/per-capita-ocean-plastic-waste.txt")


# Member 6 (pair 3) write code to load File 3 data here:#
data3 <- read_tsv("data/UN_country_population.tsv")


# Member 1 (pair 1) write code to load File 4 data here:
data4 <- read_excel("data/UN_country_region.xlsx")


```



```{r join-data, message = FALSE}
# Member 2 (pair 1) write code to create object 'plastic_data_all':
plastic_data_all <- data1



# Member 4 (pair 2) write code to join your data to 'plastic_data_all':
plastic_data_all <- data2 %>%
  select(-name) %>%
  left_join(plastic_data_all, by = "code")



# Member 6 (pair 3) write code to join your data to 'plastic_data_all':
plastic_data_all <- data3 %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")



# Member 1 (pair 1) write code to join your data to 'plastic_data_all':
plastic_data_all <- data4 %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")


```


```{r print-data, message = FALSE}
# Member 2 (pair 1) adds code here to view the first 10 rows of 'plastic_data_all'
plastic_data_all %>% head(n = 10)


```



## Exercises

### Ex 1.

```{r Ex1, message = FALSE}
# view(plastic_data_all)

#   Create a frequency table of coastal countries/territories by region.
plastic_data_all %>% group_by(region) %>% count() 

#   Which region has the most number of coastal countries/territories?
#   Africa


```



### Ex 2.

```{r Ex2, message = FALSE}

# The mismanaged plastic waste is measured in kg per capita. Add a new variable to   plastic_data_all called total_mismanage_plastic by multiplying mismanaged_plastic by population.
  plastic_data_all <- plastic_data_all %>% mutate(total_mismanaged_plastic = mismanaged_plastic * population)

# What is the mean total of mismanaged plastic waste per region?
 ex2 <- plastic_data_all %>% select("region", "total_mismanaged_plastic") 
 ex2 %>% group_by(region) %>% summarize(mean_waste = mean(total_mismanaged_plastic, na.rm = TRUE)) %>% view()
# wasnt aware that you could use mean inside summarize and rename a column in it 
 
# Which region has the highest total and which has the lowest total?
#  Asia has highest, Oceania lowest


```


### Ex 3.

```{r Ex3, message = FALSE}

# Add a new variable called pct_mismanaged_plastic_ocean to plastic_data_all that represents the amount of ocean emitted mismanaged plastic waste as a percentage of all mismanaged plastic waste.

plastic_data_all <- plastic_data_all %>% mutate(pct_mismanaged_plastic_ocean = (mismanaged_plastic_ocean / mismanaged_plastic) * 100)

# Calculate the median pct_mismanaged_plastic_ocean for each region.
med_ocean_by_region <- plastic_data_all %>% group_by(region) %>% summarise(median_ocean = median(pct_mismanaged_plastic_ocean))

# Your answer for Africa should be NaN. What does this mean and what is causing this issue? Hint: filter your data using code == "SOM".
filter(plastic_data_all, code == "SOM" ) 
# there is no mismanaged plastic


# Add the command drop_na() after computing the variable pct_mismanaged_plastic_ocean and re-evaluate the median estimates. Which region has the lowest median?
plastic_data_all <- plastic_data_all %>% mutate(pct_mismanaged_plastic_ocean = (mismanaged_plastic_ocean / mismanaged_plastic) * 100) %>% drop_na(pct_mismanaged_plastic_ocean)

med_ocean_by_region <- plastic_data_all %>% group_by(region) %>% summarise(median_ocean = median(pct_mismanaged_plastic_ocean)) %>% view()
# Africa has the lowest median





```


### Ex 4.

```{r Ex4, message = FALSE}
#The variable names in plastic_data_all are quite long, let’s do something about that.

#Use the rename() command to replace the existing variable names with something that is more concise. For example, we can contract population to pop using the following code:
plastic_data_all <- 
  plastic_data_all %>% rename(
   "pop" = "population",
   "reg" = "region",
   "mis_plas_ocean" = "mismanaged_plastic_ocean",
   "mis_plas" = "mismanaged_plastic",
   "total_mis_plas" = "total_mismanaged_plastic",
   "pct_mis_plas_ocean" = "pct_mismanaged_plastic_ocean"
 )


#Examine the names of the other variables in plastic_data_all and rename them to something that is concise yet still informative about what the variable contains. Discuss and agree in your group how best to simplify the variable names.
# could definitely abbreviate many countries such as United Kingdom to UK and United Arab Emirates to UAE




#In addition, the region name of "Latin America and The Caribbean" is much longer than the other regions, so we can consider replacing this text with a suitable acronym.
#Mutate the region variable to replace the text "Latin America and The Caribbean" with "LAC". Hint: have a look at how to use the str_replace_all() command.

plastic_data_all <- plastic_data_all %>% mutate(reg = str_replace(reg ,"Latin America and The Caribbean", "LAC")) %>% view()



```
